from arrendatools.modelo303.domain.enums import Period

from .layout import LayoutSpec, PageSpec

REGISTRO_APERTURA_FIELD_NAMES: tuple[str, ...] = (
    "registro_general_open",
    "modelo",
    "discriminante",
    "ejercicio",
    "periodo",
    "tipo_y_cierre",
)

DP30300_FIELD_NAMES: tuple[str, ...] = (
    "aux_open",
    "reserved_70",
    "version",
    "reserved_4",
    "developer_nif",
    "reserved_213",
    "aux_close",
)

DP30301_FIELD_NAMES: tuple[str, ...] = (
    "dp30301_open",
    "pagina_complementaria",
    "tipo_declaracion",
    "nif",
    "razon_social",
    "ejercicio",
    "periodo",
    "tributacion_foral",
    "registro_devolucion",
    "solo_rg",
    "autoliquidacion_conjunta",
    "criterio_caja",
    "destinatario_caja",
    "prorrata_especial",
    "revocacion_prorrata",
    "concurso",
    "fecha_concurso",
    "tipo_auto_concurso",
    "sii",
    "exencion_390",
    "operaciones_no_cero",
    "indicador_pago_gasolina",
    "casilla_150",
    "casilla_151",
    "casilla_152",
    "casilla_165",
    "casilla_166",
    "casilla_167",
    "casilla_01",
    "casilla_02",
    "casilla_03",
    "casilla_153",
    "casilla_154",
    "casilla_155",
    "casilla_04",
    "casilla_05",
    "casilla_06",
    "casilla_07",
    "casilla_08",
    "casilla_09",
    "casilla_10",
    "casilla_11",
    "casilla_12",
    "casilla_13",
    "casilla_14",
    "casilla_15",
    "casilla_156",
    "casilla_157",
    "casilla_158",
    "casilla_168",
    "casilla_169",
    "casilla_170",
    "casilla_16",
    "casilla_17",
    "casilla_18",
    "casilla_19",
    "casilla_20",
    "casilla_21",
    "casilla_22",
    "casilla_23",
    "casilla_24",
    "casilla_25",
    "casilla_26",
    "casilla_27",
    "casilla_28",
    "casilla_29",
    "casilla_30",
    "casilla_31",
    "casilla_32",
    "casilla_33",
    "casilla_34",
    "casilla_35",
    "casilla_36",
    "casilla_37",
    "casilla_38",
    "casilla_39",
    "casilla_40",
    "casilla_41",
    "casilla_42",
    "casilla_43",
    "casilla_44",
    "casilla_45",
    "casilla_46",
    "reservado_521",
    "reservado_13",
    "dp30301_close",
)

DP30302_BASE_2026: tuple[str, ...] = ()

DP30303_FIELD_NAMES: tuple[str, ...] = (
    "dp30303_open",
    "casilla_59",
    "casilla_60",
    "casilla_120",
    "casilla_122",
    "casilla_123",
    "casilla_124",
    "casilla_62",
    "casilla_63",
    "casilla_74",
    "casilla_75",
    "casilla_76",
    "casilla_64",
    "casilla_65",
    "casilla_66",
    "casilla_77",
    "casilla_110",
    "casilla_78",
    "casilla_87",
    "casilla_68",
    "casilla_108",
    "casilla_69",
    "casilla_70",
    "casilla_109",
    "casilla_112",
    "casilla_71",
    "sin_actividad",
    "rectificativa",
    "num_justificante",
    "baja_domiciliacion",
    "casilla_111",
    "motivo_rectificacion",
    "motivo_discrepancia",
    "reservado_546",
    "dp30303_close",
)

DP30304_FIELD_NAMES: tuple[str, ...] = (
    "dp30304_open",
    "pagina_complementaria",
    "codigo_actividad_principal",
    "epigrafe_iae_principal",
    "codigo_actividad_1",
    "epigrafe_iae_1",
    "codigo_actividad_2",
    "epigrafe_iae_2",
    "codigo_actividad_3",
    "epigrafe_iae_3",
    "codigo_actividad_4",
    "epigrafe_iae_4",
    "codigo_actividad_5",
    "epigrafe_iae_5",
    "marque_operaciones_terceras",
    "casilla_89",
    "casilla_90",
    "casilla_91",
    "casilla_92",
    "casilla_107",
    "casilla_80",
    "casilla_81",
    "casilla_93",
    "casilla_94",
    "casilla_83",
    "casilla_84",
    "casilla_125",
    "casilla_126",
    "casilla_127",
    "casilla_128",
    "casilla_86",
    "casilla_95",
    "casilla_96",
    "casilla_97",
    "casilla_98",
    "casilla_79",
    "casilla_99",
    "casilla_88",
    "reservado_600",
    "dp30304_close",
)

DP30305_FIELD_NAMES: tuple[str, ...] = (
    "dp30305_open",
    "pagina_complementaria",
    "casilla_500",
    "casilla_501",
    "casilla_502",
    "casilla_503",
    "casilla_504",
    "casilla_505",
    "casilla_506",
    "casilla_507",
    "casilla_508",
    "casilla_509",
    "casilla_510",
    "casilla_511",
    "casilla_512",
    "casilla_513",
    "casilla_514",
    "casilla_515",
    "casilla_516",
    "casilla_517",
    "casilla_518",
    "casilla_519",
    "casilla_520",
    "casilla_521",
    "casilla_522",
    "casilla_523",
    "casilla_524",
    "casilla_700",
    "casilla_701",
    "casilla_702",
    "casilla_703",
    "casilla_704",
    "casilla_705",
    "casilla_706",
    "casilla_707",
    "casilla_708",
    "casilla_709",
    "casilla_710",
    "casilla_711",
    "casilla_712",
    "casilla_713",
    "casilla_714",
    "casilla_715",
    "casilla_716",
    "casilla_717",
    "casilla_718",
    "casilla_719",
    "casilla_720",
    "casilla_721",
    "casilla_722",
    "casilla_723",
    "casilla_724",
    "casilla_725",
    "casilla_726",
    "casilla_727",
    "casilla_728",
    "casilla_729",
    "casilla_730",
    "casilla_731",
    "casilla_732",
    "casilla_733",
    "casilla_734",
    "casilla_735",
    "reservado_672",
    "dp30305_close",
)

DP303DID_FIELD_NAMES: tuple[str, ...] = (
    "did_open",
    "swift",
    "iban",
    "bank_name",
    "bank_address",
    "bank_city",
    "bank_country",
    "sepa",
    "reserved_617",
    "did_close",
)

REGISTRO_CIERRE_FIELD_NAMES: tuple[str, ...] = (
    "registro_general_close",
    "modelo",
    "discriminante",
    "ejercicio",
    "periodo",
    "tipo_y_cierre",
)

LAYOUT = LayoutSpec(
    pages=(
        PageSpec("registro_apertura", REGISTRO_APERTURA_FIELD_NAMES),
        PageSpec("dp30300", DP30300_FIELD_NAMES),
        PageSpec("dp30301", DP30301_FIELD_NAMES),
        PageSpec("dp30302", tuple()),
        PageSpec("dp30303", DP30303_FIELD_NAMES),
        PageSpec(
            "dp30304",
            DP30304_FIELD_NAMES,
            include_when=lambda model: model.periodo == Period.FOURTH_QUARTER,
        ),
        PageSpec(
            "dp30305",
            DP30305_FIELD_NAMES,
            include_when=lambda model: model.periodo == Period.FOURTH_QUARTER,
        ),
        PageSpec("dp303did", DP303DID_FIELD_NAMES),
        PageSpec("registro_cierre", REGISTRO_CIERRE_FIELD_NAMES),
    )
)
